# 舰艇对应目标名字
targets:
  '0': '驱护舰'
  '1': '巡洋舰'
  '2': '登陆舰'
  '3': '运输舰'
  '4': '两栖攻击舰'
  '5': '航空母舰'
  '6': '指挥舰'
  '7': '潜艇'
  '8': '货船'
  '9': '客船'
  '10': '琵琶型舰艇'
  '11': '医疗船'
  '12': '其他'

# 训练配置参数
train:
  'model_size': 'yolov5s.pt'
  'batch_size': 8
  'epochs': 100

# 程序运行中，转移，生成图片使用的临时目录
source: 'img_tmp/source'
temp: 'img_tmp/images'
result: 'img_tmp/result'
batchoutput: 'img_tmp/batchoutput'

# 亮度增强算法结果路径
lowlight: 'img_tmp/lowlight'

# 已弃用
crop_dir: 'croped'

# yolov5算法检测结果路径
output_dir: 'inference/output'

# 去雾模块相关的路径设置
fog_dir: ['img_tmp/fog/clear', 'img_tmp/fog/hazy', 'img_tmp/fog/val_list.txt', 'img_tmp/fog/', 'algorithms/RmFog/']

# 去雾模块输出地址
fog_outdoor: 'img_tmp/fog/outdoor_results'
